language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install django
  - pip install python-magic
  - pip install -e .
  - pip install coveralls
script:
  - coverage run --source=validatedfile runtests.py
notifications:
  email:
    recipients:
      - jespinog@gmail.com
      - andres.moya@kaleidos.net
    on_success: change
    on_failure: change
after_success:
  - coveralls
